### ISSUE TITLE
not boot box if flash openPli

### ISSUE THREAD

**Issue by Dima73** [oe-alliance/openmultiboot#13]
A strange problem.
Not boot box(et8000) if flash use openPli.

**Comment by arn354** [comment]
Pli has no boxbranding?

**Comment by Schimmelreiter** [comment]
Nope, they don't.

**Comment by Dima73** [comment]
I added it(boxbranding) manually.

**Comment by arn354** [comment]
Nandsim available? And there was a mountfix in oe-alliance

**Comment by Dima73** [comment]
Nandsim available(+CONFIG_MTD_NAND_NANDSIM=m/kernel-module-nandsim).
Not use mountfix in oe-alliance(+mountpoint -q "/media" || mount -t tmpfs -o size=64k tmpfs /media).
But I know about this patch.
After all, the receiver must still boot, even without this patch.
But this is not happening.

**Comment by arn354** [comment]
Then a serial log is needed to see where it stops

**Comment by Dima73** [comment]
ok

**Comment by Dima73** [comment]
If you do not insert a USB flash drive with folder /open-multiboot, the receiver is loaded.

**Comment by Dima73** [comment]
Solved.
The problem active hub + usb dvb-t Awermedia.

**Comment by Dima73** [comment]
Help to solve another problem.
Flash Pli 4.0, selecting boot name openxta 4.0
How to change the name on the Pli 4.0?

**Comment by Dima73** [comment]
solved

**Comment by Dima73** [comment]
Continuing the theme.
I need help ...
http://forums.openpli.org/topic/38058-openmultiboot-for-openpli/?view=findpost&p=493865
duo2
open-multiboot - debug: backup kernel for image 'OpenPLi-4.0-beta-vud+-----------------------------+
[VID]: VIDEO_SET_STREAMTYPE 0 
[VID]: VIDEO_SELECT_SOURCE 1  0
[VID]: VIDEO_PLAY 1  2 0
ECC failed: 0
ECC corrected: 0
Number of bad [VID]: VIDEO_CONTINUE 1  1 
blocks: 0
Numbe[VID]: VIDEO_CLEAR_BUFFER 1  1 0
r of bbt blocks: 0
Block size 131072, page size 2048, OOB size 64
Dumping data starting at 0x00000000 and ending at 0x00700000...
[VID]: VIDEO_STOP 0  1
[VID]: VIDEO_SELECT_SOURCE 0  0
open-multiboot - debug: the framebuffer device was opened successfully
open-multiboot - debug: current mode is 1920x1440, 32bpp, stride 7680
open-multiboot - debug: current mode is 1280x720, 32bpp, stride 7680
open-multiboot - debug: the framebuffer device was mapped to memory successfully
open-multiboot - debug: set color palette
open-multiboot - error: failed to set color palette
open-multiboot - debug: set manual blit
open-multiboot - debug: input device opened
open-multiboot - debug: current lcd is 140x32, 8bpp, stride 140
[VID]: VIDEO_SET_STREAMTYPE 0 
[VID]: VIDEO_SELECT_SOURCE 1  0
[VID]: VIDEO_PLAY 1  2 0
[VID]: VIDEO_CONTINUE 1  1 
[VID]: VIDEO_CLEAR_BUFFER 1  1 0
[VID]: VIDEO_STOP 0  1
[VID]: VIDEO_SELECT_SOURCE 0  0
Kernel panic - not syncing: Attempted to kill init! exitcode=0x0000000a

Rebooting in 180 seconds..
