### ISSUE TITLE
openmultiboot may load modules not aligned to the loaded kernel

### ISSUE THREAD

**Issue by dpeddi** [oe-alliance/openmultiboot#18]
it seems that omb don't load the correct kernel module

eg:
- flash blackhole
- last boot vix

box comes up with vix kernel
open-multiboot - debug: check device /dev/sdb1
open-multiboot - debug: found data on device /dev/sdb1
open-multiboot - debug: discover images
open-multiboot - debug: prepare destination
---> here i expected a "remount vix"
open-multiboot - debug: load modules
open-multiboot - debug: load vuplus-platform-util

this should enable the box to boot images with different kernel version

**Comment by arn354** [comment]
OMB should use unique kernel and kernel-modules.
On changing the image - the required kernel gets flashed by omb and the box loads that new kernel and omb mounts the according rootfs - which should have the right kernel-modules.
I never recognized nor found in any logs that a switch of a image was done only partially.

**Comment by arn354** [comment]
i just checked again - i used different kernels 
Main image in flash - kernel 4.0.1
omb image 1 - kernel 3.14.2
omb image 2 - kernel 3.3.8

All image switches were fine - if not the box would not have booted at all due to wrong rootfs (dvb.ko is located in rootfs -. using wrong dvb.ko the box would not load).

**Comment by dpeddi** [comment]
"I never recognized nor found in any log" Indeed the only log you can see is from console port. 
New vuplus boxes have custom connector, and me and few other have been so brave to build an adapter...

**Comment by arn354** [comment]
I am talking about serial console port log - not about E2 log.
Switching a image you only see in serial console log - like the rest of the regular cfe and kernel boot.

**Comment by arn354** [comment]
Is that issue still existing for vuplus?

**Comment by dpeddi** [comment]
it doesn't happened any more to me...
