### ISSUE TITLE
Make openmultiboot for openPli

### ISSUE THREAD

**Issue by Dima73** [oe-alliance/openmultiboot#20]
Please help.
The problem is related to the formuler1/3 box.

flash image openPli,usb image openATV.
Load openATV:
openPli version openmultiboot, not load openATV.
/sbin/open_multiboot size 102KB
https://github.com/OpenPLi/openpli-oe-core/blob/master/meta-openpli/recipes-openpli/openmultiboot/openmultiboot.bb
openATV version openmultiboot, load openATV OK.
/sbin/open_multiboot size 92 KB

Why such a difference of volume in the assembly?
Where is my mistake?

**Comment by arn354** [comment]
Did you solve in the meantime?

**Comment by Dima73** [comment]
No, not solved.
I can not find no one cause of the error.
