### ISSUE TITLE
 kernel-module-block2mtd

### ISSUE THREAD

**Issue by ostende** [oe-alliance/openmultiboot#26]
hello 

it can't build  kernel-module-block2mtd under oealliance for dreambox why please

**Comment by atvcaptain** [comment]
you must include inside with kernel as modul : https://github.com/oe-alliance/oe-alliance-core/blob/4.0/meta-brands/meta-dream/recipes-linux/linux-dreambox-3.2/dm800sev2/defconfig#L874

why , check old dreambox commits and read the infos

**Comment by ostende** [comment]
big thnx for your answear 

i think guetmine who not like other multiboot plugins wrok on the dmm box even for me is the best plugin is openmulti
so thank you again thank you so much i will try new build and let you know
